### ISSUE TITLE
Business Details - Woodvale & Padbury: Incorrect Enquiries Email used.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Magatelli-Holdings#37]
![image](https://cloud.githubusercontent.com/assets/13363508/13074533/04e11f9a-d4e0-11e5-910d-7c6d9ad8d596.png)

**Comment by wajahat-titan** [comment]
I need some clarity. The same email address is used for Business Details - Woodvale & Padbury

**Comment by maehtitan** [comment]
@wajahat-titan Just ignore this issue.
