### ISSUE TITLE
Banner Section: Please retain the ratio of the image when viewing in mobile, only part of the image is shown currently. I suggest to just position the text and button below the banner and the image width will be fit 100% above it in banner container

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Magatelli-Holdings#70]
Devices:
Ipad
Itouch5
Samsung E7
and all resolution

![image](https://cloud.githubusercontent.com/assets/13363508/13240859/1bf67680-da21-11e5-9c49-0671f0e038c0.png)
![image](https://cloud.githubusercontent.com/assets/13363508/13240887/5199c6f2-da21-11e5-9100-c7ed6b1b529b.png)

**Comment by maehtitan** [comment]
Images are too short in mobile views and also uploaded again a big dummy image but it looks too short still and doesn't follow the height layout based from the design

http://speedfit.stage.titanweb.com.au/

**Comment by wajahat-titan** [comment]
As height of the image is in proportion with its width so it can't be increased. Increase in the height alone may stretch the image.
