### ISSUE TITLE
Gallery - Resolution Checking: Images are not align when view in 1200 viewport below

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Magatelli-Holdings#73]
![image](https://cloud.githubusercontent.com/assets/13363508/13241325/ca7ffc14-da24-11e5-8aa6-2b5e0930e4b4.png)

**Comment by wajahat-titan** [comment]
Please upload min image size 150 x 150

**Comment by maehtitan** [comment]
But can't you make the images container height as fixed?
